name: droid_custom

task_name: custom

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [2500, 3]
      type: point_cloud
    agent_pos:
      shape: [13]
      type: low_dimx
  action:
    shape: [13]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.droid_dataset.DroidDataset
  zarr_path: data/final.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
